#!/bin/bash

## Makes reading directory listings easier
## -G: colorize output, -h: sizes human readable, -F: throws a / after a directory, * after an executable, and a @ after a symlink
alias l='ls -GFh'
#alias ls='ls -GFh'
alias lh='ls -GFhd .[^.]*'

## Chuck
alias chuck="ssh chuck && ^="

## Use Python3
#alias python="/usr/local/bin/python3"
alias pip="/usr/local/bin/pip3"
alias pip2="/Users/petermay/Library/Python/2.7/bin/pip2"

## Run gremlin client 
alias janusgraph="~/Documents/JanusGraph/0.3.0/app/janusgraph-0.3.0-hadoop2/bin/gremlin.sh"

## cd to Work directory
alias work="cd ~/Work"

## cd to icd directory
alias icd="cd ~/Work/ibm-cloud-databases/"

## cd to Janugraph/conf directory
alias conf="cd ~/Documents/Janusgraph/0.3.0/app/janusgraph-0.3.0-hadoop2/conf"

## History
alias h='history'

## Kube
alias k="kubectl"
alias ktx="kubectx"
alias kns="kubens"
alias knode="kubectl get node --label-columns eks.amazonaws.com/nodegroup | sort -k6"

## cd
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ......="cd ../../../../.."
alias -- -="cd -" # Go to previous dir with -
alias doc="cd ~/Documents"
alias dow="cd ~/Downloads"
alias des="cd ~/Desktop"
alias proj="cd ~/Projects"
alias proj='DIR=$(fd --type d -d 1 . $HOME/Projects -x echo | fzf --delimiter / --with-nth -1) && cd $DIR'
alias dot="cd ~/.dotfiles"
alias scratch="cd ~/Documents/scratch"

## git
alias g="git"

## grep
alias G="| grep -i"

# Trim new lines and copy to clipboard
# alias c="tr -d '\n' | pbcopy"

## ps aux
alias p="ps aux | grep"

## cat -> bat
alias cat="bat --theme TwoDark -p"

## find file
alias f="find . -name "

## open in finder
alias finder="open -a Finder ./"

## show alias
alias showa="cat ~/.dotfiles/bash/aliases"

## cd to ycsb
alias yahoo="cd /opt/ycsb/ycsb-0.15.0"

## URL encode
alias url-decode='python3 -c "import sys, urllib.parse as ul; print(ul.unquote_plus(sys.argv[1]))"'
alias url-encode='python3 -c "import sys, urllib.parse as ul; print(ul.quote_plus(sys.argv[1]))"'

## mal
# alias mal='source ~/Work/Compose/config/.malpractice && cd ~/Work/Compose/malpractice && bundle exec mal'
alias mal='source ~/Work/Compose/config/.malpractice && bundle exec ~/Work/Compose/malpractice/mal'

## ibmcloud
alias ic='ibmcloud'

alias fastai='ssh pmay@169.48.245.197'

alias ic='ibmcloud'

alias sml='rlwrap sml'

alias resetmouse='printf "\e[?1000l"'

alias c='DIR=`fd --type d -d 1 . $HOME/Work/Compose | fzf --delimiter / --with-nth -1` && if [ -z $DIR ]; then cd ~/Compose/Work; else cd "$DIR"; fi'

alias zload="source $HOME/.zshrc" # reload .zshrc

alias surgery-table='source ~/Work/Compose/config/.surgery-table && ~/Work/Compose/surgery-table/surgery-table'

alias resetk='export KUBECONFIG=~/Work/Compose/k8s/kubeconfigs/kubeconfig.yaml'

alias switchu='"/System/Library/CoreServices/Menu Extras/User.menu/Contents/Resources/CGSession" -suspend'

alias ctags="`brew --prefix`/bin/ctags"

alias gogo="cd ~/go/src/github.ibm.com/compose"

alias console="~/Work/Compose/scripts/get-console"

alias gru='~/Work/Compose/scripts/get-console gru web "bundle exec rake console"'

alias subl='/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl'

alias code='/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code'

alias vim='nvim'

alias v='print -z -- nvim $(fzf)'


### NEW STUFF

alias snippets="cd \"/Users/petermay/Library/Mobile Documents/iCloud~md~obsidian/Documents/Pete's mobile vault/.obsidian/snippets\""

