#!/bin/bash

## Makes reading directory listings easier
## -G: colorize output, -h: sizes human readable, -F: throws a / after a directory, * after an executable, and a @ after a symlink
alias l='ls -GFh'
#alias ls='ls -GFh'
alias lh='ls -GFhd .[^.]*'

## Source bash_profile
alias reload="source ~/.bash_profile && zload"

## Chuck
alias chuck="ssh chuck && ^="

## Use Python3
#alias python="/usr/local/bin/python3"
alias pip="/usr/local/bin/pip3"

## Run gremlin client 
alias janusgraph="~/Documents/JanusGraph/0.3.0/app/janusgraph-0.3.0-hadoop2/bin/gremlin.sh"

## cd to Work directory
alias work="cd ~/Work"

## cd to Janugraph/conf directory
alias conf="cd ~/Documents/Janusgraph/0.3.0/app/janusgraph-0.3.0-hadoop2/conf"

## History
alias h='history'

## Kube
alias kb="kubectl"
alias ktx="kubectx"
alias kns="kubens"

## cd
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ......="cd ../../../../.."
alias -- -="cd -" # Go to previous dir with -
alias doc="cd ~/Documents"
alias dow="cd ~/Downloads"
alias des="cd ~/Desktop"
alias proj="cd ~/Projects"
alias dot="cd ~/.dotfiles"
alias scratch="cd ~/Documents/scratch"

## git
alias g="git"

## grep
alias G="| grep -i"

# Trim new lines and copy to clipboard
alias c="tr -d '\n' | pbcopy"

## ps aux
alias p="ps aux | grep"

## cat -> bat
alias cat="bat --theme TwoDark -p"

## kill
alias k="kill -9"

## find file
alias f="find . -name "

## open in finder
alias finder="open -a Finder ./"

## show alias
alias showa="cat ~/.dotfiles/bash/aliases"

## cd to ycsb
alias yahoo="cd /opt/ycsb/ycsb-0.15.0"

## URL encode
alias url-decode='python3 -c "import sys, urllib.parse as ul; print(ul.unquote_plus(sys.argv[1]))"'
alias url-encode='python3 -c "import sys, urllib.parse as ul; print(ul.quote_plus(sys.argv[1]))"'

## mal
alias mal='source ~/Work/Compose/config/.malpractice && cd ~/Work/Compose/malpractice && bundle exec mal'

## ibmcloud
alias ic='ibmcloud'

alias fastai='ssh pmay@169.48.245.197'

alias ic='ibmcloud'

alias sml='rlwrap sml'

alias resetmouse='printf "\e[?1000l"'

alias compose='DIR=`fd --type d -d 1 . $HOME/Work/Compose | fzf --delimiter / --with-nth -1` && if [ -z $DIR ]; then cd ~/Compose/Work; else cd "$DIR"; fi'

alias zload="source $HOME/.zshrc" # reload .zshrc

alias surgery-table='source ~/Work/Compose/config/.surgery-table && ~/Work/Compose/surgery-table/surgery-table'

alias resetkb='export KUBECONFIG=~/Work/Compose/k8s/kubeconfigs/kubeconfig.yaml'

alias switchu='"/System/Library/CoreServices/Menu Extras/User.menu/Contents/Resources/CGSession" -suspend'

alias ctags="`brew --prefix`/bin/ctags"
