#!/bin/bash

### base64 encode/decode
function bd () {
  echo $1 | base64 -D
}
function be () {
  echo -n $1 | base64
}

#   mans:   Search manpage given in agument '1' for term given in argument '2' (case insensitive)
#           displays paginated result with colored search terms and two lines surrounding each hit.            Example: mans mplayer codec
#   --------------------------------------------------------------------
function mans () {
  man $1 | grep $2
}

#   showa: to remind yourself of an alias (given some part of it)
#   ------------------------------------------------------------
function showa () {
  /usr/bin/grep --color=always -i -a1 $@ ~/Library/init/bash/aliases.bash | grep -v '^\s*$' | less -FSRXc ;
}

# connect to gru hosts
function conn () {
  ssh -t chuck "source ~/functions/sshs ; sshs $1"
}

# print k8s secret
function ks () {
  kubectl get secret $1 -o yaml | print_secret.rb
}

# print k8s secret
function kcm () {
  kubectl get cm $1 -o yaml | print_cm.rb
}

# print k8s configmap
# function kcm () {
  # kubectl get cm $1 -o yaml
# }

# print k8s pod logs
function kl () {
  kubectl logs $1 -f
}

# print k8s kubetail
function ktail () {
  kubetail $1 -c $1
}

# print k8s pod logs
function kpo () {
  kubectl get po -l release=$1
}

# print pod logs - select compose container
function klogs () {
  kubectl logs $1 "${1%-*-*}" -f
}
