#!/bin/bash

export PATH="/usr/local/opt/python/libexec/bin:/usr/local/share/python:$PATH"

export PATH="/usr/bin:/bin:/usr/sbin:/sbin:$PATH"

export PATH="/usr/local/go/bin:$PATH"

export PATH="/usr/local/bin:/usr/local/sbin:$PATH"

export PATH="/usr/local/opt/node@8/bin:$PATH"

export PATH="/Applications/Visual Studio Code.app/Contents/Resources/app/bin:$PATH"

export PATH="~/.rbenv/bin:$PATH"

export PATH="/usr/local/smlnj/bin:$PATH"

